state_machine:
  initial_state: neutral
  hysteresis: 0.05

policy:
  cautious:
    lateral_step_m: 0.05
    pan_step_deg: 5.0
  neutral:
    lateral_step_m: 0.1
    pan_step_deg: 10.0
  exploratory:
    lateral_step_m: 0.2
    pan_step_deg: 15.0

